Resources:
  ItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.12
      CodeUri: .
      Events:
        ItemsApi:
          Type: Api
          Properties:
            Path: /{proxy+}  # This catches all paths, including "/"
            Method: ANY