name: Deploy Lambda and Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

  deploy:
    name: Deploy AWS Lambda
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies and Package Layer
        run: |
          mkdir python
          pip install -r requirements.txt -t python/
          zip -r dependencies.zip python/

      - name: Zip Lambda Function Code
        run: zip function.zip app.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Adjust as necessary

      - name: Deploy Lambda Layer
        run: |
          aws lambda publish-layer-version \
            --layer-name sasss_backend_dependencies \
            --zip-file fileb://dependencies.zip

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name sasss_backend \
            --zip-file fileb://function.zip